kits:
  logs:
    - durability: '0'
      id: log
      isNeg: ''
    - durability: '0'
      id: log
      isNeg: ''
  wools:
    - durability: '2'
      id: wool
      isNeg: ''
    - durability: '3'
      id: wool
      isNeg: ''
  prokit228:
    - durability: '0'
      id: stone
      isNeg: 'true'
    - durability: '0'
      id: dirt
      isNeg: ''