name: RandomTools
version: 0.0.4
main: dev.hevav.randomtools.RandomTools
api-version: 1.16
commands:
  #give tools
  rgive:
    description: Do random give
    usage: /rgive [player] [limit] [item] [item2] (item3..)
    permission: randomtools.give.any
  rkitadd:
    description: Add a kit to the config
    usage: /rkitadd [name] [item] [item2] (item3..)
    permission: randomtools.give.any
  rkitremove:
    description: Remove a kit from the config
    usage: /rkitremove [name]
    permission: randomtools.give.any
  rkit:
    description: Random give from the kit from the config
    usage: /rkit [player] [kit] [limit]
    permission: randomtools.give.kit
  rkitloop:
    description: Loops random give from the kit from the config
    usage: /rkitloop [player] [kit] [limit] [interval]
    permission: randomtools.give.kit
  rgivecenter:
    description: Set center(in center you have more resources)
    usage: /rgivecenter [radius * block quanity]
    permission: randomtools.give.any
  #team tools
  rteam:
    description: Do an operation to the team
    usage: /rteam [name or *] [operation]
    permission: randomtools.team.op
  rteamcreate:
    description: Creates random teams
    usage: /rteamcreate [limit]
    permission: randomtools.team.any
  rteamremove:
    description: Removes random teams
    usage: /rteamremove [name or *]
    permission: randomtools.team.any
permissions:
  randomtools.give.any:
    default: op
    description: Give any block(/rgive), add/remove kits
  randomtools.give.kit:
    default: op
    description: Give the kit(/rkit)
  randomtools.team.any:
    default: op
    description: Create/Remove the random team
  randomtools.team.op:
    default: op
    description: Do an operation for the team